CREATE TABLE IF NOT EXISTS etf_enrichment (
    asset_id bigint PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
    isin text NOT NULL,
    name text,
    description text,
    index_tracked text,
    investment_focus text,
    country_weights jsonb,
    sector_weights jsonb,
    top_holdings jsonb,
    holdings_date text,
    replication_method text,
    distribution_policy text,
    distribution_frequency text,
    fund_currency text,
    currency_hedged boolean,
    domicile text,
    fund_provider text,
    fund_size_eur numeric,
    ter numeric,
    volatility_1y numeric,
    sustainability boolean,
    inception_date text,
    source text DEFAULT 'justetf',
    fetched_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_etf_enrichment_isin ON etf_enrichment(isin);
